name: Stage Hunter Bot - Auto Scan

on:
  schedule:
    - cron: '0 */2 * * *' # Exécution toutes les 2 heures
  workflow_dispatch:      # Permet de lancer manuellement depuis l'onglet Actions de GitHub

jobs:
  scan:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Scraper
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          DIRECT_URL: ${{ secrets.DIRECT_URL }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          SEARCH_KEYWORDS: ${{ secrets.SEARCH_KEYWORDS }}
          SEARCH_LOCATIONS: ${{ secrets.SEARCH_LOCATIONS }}
        run: python main.py search
